precos = [45.12, 85.12, 12.98,78.63, 103.45, 5.98, 12.98]
 
print(precos)
print(precos[2])
print(precos[-3])
print(len(precos))
print(max(precos))
print(min(precos))
print(sum(precos))
print(sum(precos)/len(precos))
print(precos.index(85.12))
print(precos.count(12.98))
 
precos.append(25.64)
print(precos)
precos.extend([56.45, 32.78])
print(precos)
precos.remove(85.12)
print(precos)
precos.insert(2,45.63)
print(precos)
ultimo = precos.pop()
print(ultimo)
print(precos)
precos.sort()
print(precos)
#precos.sort(reverse=True)
precos.reverse()
print(precos)
 
precos2 = precos.copy()
precos.clear()
print(precos)
print(precos2)
